plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.groovyapp'
    compileSdk 34

    defaultConfig {
        applicationId 'com.example.groovyapp'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled true
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.11.0'
    implementation project(':core')
}
