import type { ContextCapsule, RetrievalAuditRecord } from '../../src/context/types.js'

export function baseCapsule(overrides: Partial<ContextCapsule> = {}): ContextCapsule {
  return {
    schemaVersion: '1.0.0',
    generatedAt: '2026-01-01T00:00:00.000Z',
    tool: { name: 'my-dev-kit', version: '1.6.1' },
    request: {
      originalQuery: 'sample query',
      normalizedQuery: 'sample query',
      mode: 'feature-add',
      requestedOutputPath: 'context-capsule.json',
    },
    index: {
      indexPath: 'index',
      manifestPath: 'index/manifest.json',
      artifactRefs: [],
    },
    limits: { maxCandidateFiles: null, maxSourceSlices: null, maxGraphNodes: null, maxGraphEdges: null },
    requiredContext: [],
    optionalSupportContext: [],
    droppedContext: [],
    warnings: [],
    contextAdequacy: {
      status: 'context sufficient with listed assumptions',
      summary: 'sample summary',
      assumptions: [],
      gaps: [],
    },
    queryPlan: {
      originalQuery: 'sample query',
      normalizedQuery: 'sample query',
      mode: 'feature-add',
      searchQueries: ['sample query'],
      terms: {
        raw: [],
        quotedPhrases: [],
        pathLike: [],
        symbolLike: [],
        routeLike: [],
        commandLike: [],
        artifactLike: [],
        classificationLike: [],
      },
    },
    candidateFiles: [],
    candidateNodes: [],
    focus: {
      focusNodeId: null,
      focusFilePath: null,
      selectionMode: 'none',
      confidence: 'none',
      reasons: [],
      ambiguityNotes: [],
      warnings: [],
    },
    selectedGraph: { nodes: [], edges: [], omittedNodeCount: 0, omittedEdgeCount: 0, warnings: [] },
    retention: {
      retainedCandidateCount: 0,
      droppedCandidateCount: 0,
      retainedGraphNodeCount: 0,
      droppedGraphNodeCount: 0,
      retainedGraphEdgeCount: 0,
      droppedGraphEdgeCount: 0,
      capSettings: { maxCandidateFiles: null, maxGraphNodes: null, maxGraphEdges: null },
    },
    selectedSource: { slices: [], omittedSliceCount: 0, totalSelectedLines: 0, maxSourceSlices: 8, warnings: [], skipped: [] },
    selectedSourceBundles: { bundles: [], omittedBundleCount: 0, totalSelectedLines: 0, warnings: [] },
    semanticSummary: {
      available: false,
      roles: [],
      artifactRefs: [],
      evidenceRefs: [],
      summariesByNode: {},
      summariesByFile: {},
      warnings: [],
    },
    classificationSummary: {
      available: false,
      classificationArtifactPath: null,
      roles: [],
      refs: [],
      editGuidance: [],
      readiness: [],
      riskLabels: [],
      uncertainty: [],
      summariesByNode: {},
      summariesByFile: {},
      warnings: [],
    },
    artifactReferenceSummary: [],
    pruning: {
      policyVersion: '1.0.0',
      retainedCounts: { candidateFiles: 0, candidateNodes: 0, graphNodes: 0, graphEdges: 0, sourceSlices: 0, sourceBundles: 0 },
      droppedCounts: { candidateFiles: 0, candidateNodes: 0, graphNodes: 0, graphEdges: 0, sourceSlices: 0, sourceBundles: 0 },
      capSettings: { maxCandidateFiles: null, maxGraphNodes: null, maxGraphEdges: null, maxSourceSlices: 8 },
      retainedReasons: [],
      droppedReasons: [],
      warnings: [],
    },
    conflicts: { status: 'none', conflicts: [], warnings: [] },
    modeEffects: { mode: 'feature-add', applied: false, effects: [], warnings: [] },
    sourceControl: { enabled: true, reason: 'Bounded source evidence is enabled by default.' },
    ...overrides,
  }
}

export function baseAudit(overrides: Partial<RetrievalAuditRecord> = {}): RetrievalAuditRecord {
  return {
    schemaVersion: '1.0.0',
    generatedAt: '2026-01-01T00:00:00.000Z',
    tool: { name: 'my-dev-kit', version: '1.6.1' },
    request: {
      originalQuery: 'sample query',
      normalizedQuery: 'sample query',
      mode: 'feature-add',
      requestedOutputPath: 'context-capsule.json',
    },
    index: { indexPath: 'index', manifestPath: 'index/manifest.json' },
    steps: [],
    fallbacks: [],
    fullFileReadRecommendations: [],
    warnings: [],
    contextAdequacy: {
      status: 'context sufficient with listed assumptions',
      summary: 'sample summary',
      assumptions: [],
      gaps: [],
    },
    ...overrides,
  }
}
